name: consul-client
summary: Consul is a tool for service discovery, monitoring and configuration.
description: |
  Consul is a distributed, highly available, and data center aware solution to
  connect and configure applications across dynamic, distributed infrastructure.
base: core24
version: "1.19.2"
license: BUSL-1.1

grade: devel # still needing to develop this snap further
confinement: strict

platforms:
  amd64:
  arm64:

apps:
  consul-client:
    command: bin/consul
    plugs:
      - network
  consul:
    daemon: simple
    command: commands/consul-wrapper
    install-mode: disable
    restart-condition: on-failure
    plugs:
      - network
      - network-bind

parts:
  consul:
    build-snaps:
      - go/latest/stable
    plugin: make
    source-type: git
    source: https://github.com/hashicorp/consul.git
    source-tag: "v1.19.2"
    override-build: |
      set -eux
      cd $CRAFT_PART_SRC
      make
      strip bin/consul
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp ./bin/consul $CRAFT_PART_INSTALL/bin/consul
    stage:
      - bin/consul

  wrappers:
    plugin: dump
    source: snap-wrappers/
    organize:
      "*": commands/

plugs:
  consul-socket:
    interface: content
    content: consul-unix-sock
    target: $SNAP_DATA
