name: consul-client
base: core22
version: "2024.1"
summary: Snap for running HashiCorp Consul in client mode for OpenStack Sunbeam
description: |
  The OpenStack Sunbeam project uses HashiCorp Consul to provide support
  for OpenStack Masakari. OpenStack Masakari provides automated recovery
  for OpenStack virtual machine instances in the event of cloud
  failures. OpenStack Masakari can use HashiCorp Consul to monitor
  the status of OpenStack hypervisor hosts. This snap provides Consul
  for use in client mode.

grade: devel # still needing to develop this snap further
confinement: strict

parts:
  consul: # Consul builds using make and not a simple golang build
    build-packages:
    - make 
    build-snaps:
    - go/latest/stable
    plugin: nil
    source-type: git
    source: https://github.com/hashicorp/consul.git
    source-tag: "v1.19.2"
    override-build: |
      set -eux

      cd $CRAFT_PART_SRC

      make

      cp ./bin/consul $CRAFT_PART_INSTALL/consul
    stage:
    - consul

apps:
  consul-client: # consul needs to be able to bind to a listening port
    command: consul
    plugs:
    - network
    - network-bind
